### ISSUE TITLE
steps_rejected in basic_tau_hybrid referenced before assignment

### ISSUE THREAD

**Issue by hodgespodge** [GillesPy2/GillesPy2#192]
When I ran run_tests.py in 1_2_release:

ERROR: test_extraneous_args (test_all_solvers.TestAllSolvers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/samuelhodges/PycharmProjects/GillesPy2/test/test_all_solvers.py", line 60, in test_extraneous_args
    results = model.run(solver=solver, nonsense='ABC')
  File "../gillespy2/core/gillespy2.py", line 457, in run
    solver_results = solver.run(model=self, t=self.tspan[-1], increment=self.tspan[-1] - self.tspan[-2], **solver_args)
  File "../gillespy2/solvers/numpy/basic_tau_hybrid_solver.py", line 481, in run
    steps_rejected +=1
UnboundLocalError: local variable 'steps_rejected' referenced before assignment

----------------------------------------------------------------------

**Comment by seanebum** [comment]
fixed in commit fff641d1c99942a37a01a035b6e6d67426b0a07d
