### ISSUE TITLE
SSACsolver errors on Windows: ValueError: buffer size must be a multiple of element size

### ISSUE THREAD

**Issue by briandrawert** [GillesPy2/GillesPy2#417]
```
2020-08-04 02:16:26,835 - root - WARNING - Please install/configure 'g++' and 'make' on your system, to ensure that GillesPy2 C solvers will run properly.
2020-08-04 02:16:26,835 - root - WARNING - Please install/configure 'g++' and 'make' on your system, to ensure that GillesPy2 C solvers will run properly.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\gillespy2\core\model.py", line 801, in run
    timeout=timeout, **solver_args)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\gillespy2\solvers\cpp\variable_ssa_c_solver.py", line 298, in run
    len(model.listOfSpecies), pause=pause)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\gillespy2\solvers\utilities\solverutils.py", line 94, in _parse_binary_output
    data = np.frombuffer(results_buffer, dtype=np.float64)
ValueError: buffer size must be a multiple of element size

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gillespie.py", line 26, in <module>
    results = model.run()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\gillespy2\core\model.py", line 813, in run
    "argument 'solver={}' to run() failed.  Reason Given: {}".format(solver, e))
gillespy2.core.gillespyError.SimulationError: argument 'solver=<class 'gillespy2.solvers.cpp.variable_ssa_c_solver.VariableSSACSolver'>' to run() failed.  Reason Given: buffer size must be a multiple of element size
```

**Comment by seanebum** [comment]
Should be resolved as of 1.5.3
